name: impfbot
version: 1.1.1
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: Package description here.
requirements:
- python ^3.5
- sqlalchemy
- sqlalchemy-repr
- python-telegram-bot
- requests
- bs4 ^0.0.1
- databind.core ^0.11.0
- databind.yaml ^0.1.3
test-requirements:
- pytest
dev-requirements:
- sqlalchemy-stubs
- types-cachetools
- types-requests
- types-pkg_resources
render-requirements-txt: true
entrypoints:
  impfbot.api.IPlugin:
  - dachau = impfbot.contrib.de.bavaria.dachau:DachauMedPlugin
